### ISSUE TITLE
html兼容性问题

### ISSUE THREAD

**Issue by matolv** [GamemakerChina/gmchina_xiuno_editormd#10]
![](https://i.imgur.com/NXrMLkc.png)

Imgur的分享连接和youtube视频都显示不出来，不知道是设置原因还是插件本身issue，文字没问题。html解析选择开也是一样，xiuno版本4.04

**Comment by LiarOnce** [comment]
有F12输出日志吗？

**Comment by matolv** [comment]
![Imgur](https://i.imgur.com/VtXw7Q5.png)
你是指截图这个日志么？我不太懂F12控制台，开发员你可以自己试下

**Comment by LiarOnce** [comment]
YouTube的视频是因为安全因素将iframe标签过滤掉了，所以输出是没有YouTube视频的
Imgur的话则是因为GFW的原因了

**Comment by matolv** [comment]
多谢回复，我刚才又试了下，应该不是GFW问题吧，用$$访问也加载不出来的，而且imgur标签会导致下面的markdown图片也失效。

PS. 我有一次不知道怎么设置或者加载了其他插件什么的，导致imgur和youtube都能显示了，但是markdown全失效了，比如`**bold**` 之类

**Comment by LiarOnce** [comment]
1，因为Imgur提供的代码包含有js脚本引用，同样是因为安全原因被过滤。如果你需要使用Imgur提供的js脚本需要在当前主题页脚代码中单独插入Imgur提供的js脚本
2，有可能是因为其他插件将输出修改为 `message` （用户原始输入）

**Comment by matolv** [comment]
非常感谢解答
